In [1]:
## load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import datetime

## set display options
# Display the complete values in the DataFrame
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)

In [2]:
## load data
houses_for_sale = pd.read_csv('houses_sale_kenya.csv')
houses_for_sale.head()

,listing_title,price,land_area,bedrooms,bathrooms,agent_name,date_created,internal_features,external_features,nearby,link
0,4 Bed Townhouse with En Suite in Westlands Area,"\nKSh 40,000,000\n",NaN,4.0,4.0,Origin Homes,04/07/2023,"\nAlarm\n,\nBackup Generator\n,\nEn Suite\n,\nFibre Internet\n,\nWalk In Closet\n","\nBBQ\n,\nParking\n,\nStaff Quarters\n,\nCCTV\n,\nElectric Fence\n,\nBorehole\n,\nGarden\n","\nBus Stop\n,\nShopping Centre\n,\nGolf Course\n,\nScenic View\n,\nHospital\n,\nSchool\n",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-westlands-area-3612765
1,4 Bed Townhouse with En Suite in Redhill,"\nKSh 40,000,000\n",NaN,4.0,5.0,Edlon Group Limited,07/07/2023,\nEn Suite\n,"\nElectric Fence\n,\nGarden\n,\nParking\n",\nScenic View\n,https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-red-hill-4-3460895
2,4 Bed House with Walk In Closet at Bamburi Mwisho,"\nKSh 15,000,000\n",NaN,4.0,5.0,Abdul Kalume Realtors,04/07/2023,"\nFurnished\n,\nWalk In Closet\n","\nBalcony\n,\nParking\n,\nStaff Quarters\n","\nBus Stop\n,\nHospital\n,\nSchool\n,\nGolf Course\n,\nScenic View\n",https://www.buyrentkenya.com/listings/furnished-4-bedroom-house-for-sale-bamburi-1-3482311
3,4 Bed Townhouse with En Suite at Olive Place Townhomes,"\nKSh 12,500,000\n",NaN,4.0,3.0,Olive Place,30/06/2023,"\nEn Suite\n,\nService Charge Included\n,\nWalk In Closet\n,\nFibre Internet\n","\nBalcony\n,\nCCTV\n,\nElectric Fence\n,\nBorehole\n,\nParking\n","\nSchool\n,\nHospital\n,\nBus Stop\n,\nShopping Centre\n,\nScenic View\n",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-gikambura-1-3578132
4,6 Bed Villa with Swimming Pool at Nanyuki,"\nKSh 60,000,000\n",\n,6.0,6.0,Precious Wanjiru,24/05/2023,"\nBalcony\n,\nGym\n,\nParking\n,\nSwimming Pool\n,\nGarden\n,\nBorehole\n","\nScenic View\n,\nGolf Course\n",NaN,https://www.buyrentkenya.com/listings/6-bedroom-villa-for-sale-nanyuki-3601569

- The dataset as scraped is quite not in a very useful version
- We are going to clean it up and make it more useful for our analysis

In [3]:
## strip all the columns

## apply strip_all function
houses_for_sale_df = houses_for_sale.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [4]:
houses_for_sale_df.dtypes

listing_title         object
price                 object
land_area             object
bedrooms             float64
bathrooms            float64
agent_name            object
date_created          object
internal_features     object
external_features     object
nearby                object
link                  object
dtype: object

In [5]:
## clean the price column
## remove the Kshs and 

def clean_price(price):
    price = str(price).strip()
    price = re.sub(r'[^0-9]', '', str(price))
    if len(price) > 0:
        price = int(price)
    else:
        price = np.nan

    return price

# houses_for_sale_df['price'] = houses_for_sale_df['price'].str.replace('Kshs', '')
# houses_for_sale_df['price'] = houses_for_sale_df['price'].str.replace(',', '')

houses_for_sale_df['price'] = houses_for_sale_df['price'].apply(clean_price)

In [6]:
houses_for_sale_df.head()

,listing_title,price,land_area,bedrooms,bathrooms,agent_name,date_created,internal_features,external_features,nearby,link
0,4 Bed Townhouse with En Suite in Westlands Area,40000000.0,NaN,4.0,4.0,Origin Homes,04/07/2023,"Alarm\n,\nBackup Generator\n,\nEn Suite\n,\nFibre Internet\n,\nWalk In Closet","BBQ\n,\nParking\n,\nStaff Quarters\n,\nCCTV\n,\nElectric Fence\n,\nBorehole\n,\nGarden","Bus Stop\n,\nShopping Centre\n,\nGolf Course\n,\nScenic View\n,\nHospital\n,\nSchool",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-westlands-area-3612765
1,4 Bed Townhouse with En Suite in Redhill,40000000.0,NaN,4.0,5.0,Edlon Group Limited,07/07/2023,En Suite,"Electric Fence\n,\nGarden\n,\nParking",Scenic View,https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-red-hill-4-3460895
2,4 Bed House with Walk In Closet at Bamburi Mwisho,15000000.0,NaN,4.0,5.0,Abdul Kalume Realtors,04/07/2023,"Furnished\n,\nWalk In Closet","Balcony\n,\nParking\n,\nStaff Quarters","Bus Stop\n,\nHospital\n,\nSchool\n,\nGolf Course\n,\nScenic View",https://www.buyrentkenya.com/listings/furnished-4-bedroom-house-for-sale-bamburi-1-3482311
3,4 Bed Townhouse with En Suite at Olive Place Townhomes,12500000.0,NaN,4.0,3.0,Olive Place,30/06/2023,"En Suite\n,\nService Charge Included\n,\nWalk In Closet\n,\nFibre Internet","Balcony\n,\nCCTV\n,\nElectric Fence\n,\nBorehole\n,\nParking","School\n,\nHospital\n,\nBus Stop\n,\nShopping Centre\n,\nScenic View",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-gikambura-1-3578132
4,6 Bed Villa with Swimming Pool at Nanyuki,60000000.0,,6.0,6.0,Precious Wanjiru,24/05/2023,"Balcony\n,\nGym\n,\nParking\n,\nSwimming Pool\n,\nGarden\n,\nBorehole","Scenic View\n,\nGolf Course",NaN,https://www.buyrentkenya.com/listings/6-bedroom-villa-for-sale-nanyuki-3601569

In [7]:
## for interio, exterior, nearby make it a statement seperated by commas - remove the \n and \t
def clean_features(features):
    features = re.sub(r'[\n\t]', ',', str(features))
    features = re.sub(r',+', ', ', str(features))
    return features


houses_for_sale_df[['internal_features', 'external_features', 'nearby']] = houses_for_sale_df[['internal_features', 'external_features', 'nearby']].applymap(clean_features)

In [8]:
## convert date to datetime
houses_for_sale_df['date_created'] = pd.to_datetime(houses_for_sale_df['date_created'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')

In [9]:
houses_for_sale_df.head()

,listing_title,price,land_area,bedrooms,bathrooms,agent_name,date_created,internal_features,external_features,nearby,link
0,4 Bed Townhouse with En Suite in Westlands Area,40000000.0,NaN,4.0,4.0,Origin Homes,2023-07-04,"Alarm, Backup Generator, En Suite, Fibre Internet, Walk In Closet","BBQ, Parking, Staff Quarters, CCTV, Electric Fence, Borehole, Garden","Bus Stop, Shopping Centre, Golf Course, Scenic View, Hospital, School",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-westlands-area-3612765
1,4 Bed Townhouse with En Suite in Redhill,40000000.0,NaN,4.0,5.0,Edlon Group Limited,2023-07-07,En Suite,"Electric Fence, Garden, Parking",Scenic View,https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-red-hill-4-3460895
2,4 Bed House with Walk In Closet at Bamburi Mwisho,15000000.0,NaN,4.0,5.0,Abdul Kalume Realtors,2023-07-04,"Furnished, Walk In Closet","Balcony, Parking, Staff Quarters","Bus Stop, Hospital, School, Golf Course, Scenic View",https://www.buyrentkenya.com/listings/furnished-4-bedroom-house-for-sale-bamburi-1-3482311
3,4 Bed Townhouse with En Suite at Olive Place Townhomes,12500000.0,NaN,4.0,3.0,Olive Place,2023-06-30,"En Suite, Service Charge Included, Walk In Closet, Fibre Internet","Balcony, CCTV, Electric Fence, Borehole, Parking","School, Hospital, Bus Stop, Shopping Centre, Scenic View",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-gikambura-1-3578132
4,6 Bed Villa with Swimming Pool at Nanyuki,60000000.0,,6.0,6.0,Precious Wanjiru,2023-05-24,"Balcony, Gym, Parking, Swimming Pool, Garden, Borehole","Scenic View, Golf Course",nan,https://www.buyrentkenya.com/listings/6-bedroom-villa-for-sale-nanyuki-3601569

In [10]:
## house with no date

houses_for_sale_df[houses_for_sale_df['date_created'].isnull()]

,listing_title,price,land_area,bedrooms,bathrooms,agent_name,date_created,internal_features,external_features,nearby,link
308,4 Bed Townhouse with En Suite at Loresho Ridge,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,https://www.buyrentkenya.com/townhouses-for-sale/nairobi/westlands/loresho/4-bedroom
632,6 Bed House with En Suite in Karen,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,https://www.buyrentkenya.com/houses-for-sale/nairobi/karen/4-bedroom
893,5 Bed House with En Suite at Muthaiga Garden,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,https://www.buyrentkenya.com/houses-for-sale/nairobi/muthaiga/4-bedroom
1012,5 Bed House with En Suite at Lower Kabete,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,https://www.buyrentkenya.com/houses-for-sale/nairobi/westlands/lower-kabete/4-bedroom
1202,4 Bed House with Garden at Kahawa Near Jacaranda Estate,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,https://www.buyrentkenya.com/houses-for-sale/nairobi/roysambu/kahawa-west/4-bedroom
2113,4 Bed Villa with En Suite in Kiambu Road,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,https://www.buyrentkenya.com/villas-for-sale/nairobi/kiambu-road/4-bedroom

- The houses that have missing date created are not part of the data that we requested
- The links to these houses are quite different from the ones that we requested
- This made them to have other variables to have missing
- We are going to drop them

In [11]:
## drop the houses with no date
houses_for_sale_df = houses_for_sale_df.dropna(subset=['date_created'])

In [12]:
## drop the land_area column
houses_for_sale_df = houses_for_sale_df.drop(columns=['land_area'])

In [13]:
houses_for_sale_df.head()

,listing_title,price,bedrooms,bathrooms,agent_name,date_created,internal_features,external_features,nearby,link
0,4 Bed Townhouse with En Suite in Westlands Area,40000000.0,4.0,4.0,Origin Homes,2023-07-04,"Alarm, Backup Generator, En Suite, Fibre Internet, Walk In Closet","BBQ, Parking, Staff Quarters, CCTV, Electric Fence, Borehole, Garden","Bus Stop, Shopping Centre, Golf Course, Scenic View, Hospital, School",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-westlands-area-3612765
1,4 Bed Townhouse with En Suite in Redhill,40000000.0,4.0,5.0,Edlon Group Limited,2023-07-07,En Suite,"Electric Fence, Garden, Parking",Scenic View,https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-red-hill-4-3460895
2,4 Bed House with Walk In Closet at Bamburi Mwisho,15000000.0,4.0,5.0,Abdul Kalume Realtors,2023-07-04,"Furnished, Walk In Closet","Balcony, Parking, Staff Quarters","Bus Stop, Hospital, School, Golf Course, Scenic View",https://www.buyrentkenya.com/listings/furnished-4-bedroom-house-for-sale-bamburi-1-3482311
3,4 Bed Townhouse with En Suite at Olive Place Townhomes,12500000.0,4.0,3.0,Olive Place,2023-06-30,"En Suite, Service Charge Included, Walk In Closet, Fibre Internet","Balcony, CCTV, Electric Fence, Borehole, Parking","School, Hospital, Bus Stop, Shopping Centre, Scenic View",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-gikambura-1-3578132
4,6 Bed Villa with Swimming Pool at Nanyuki,60000000.0,6.0,6.0,Precious Wanjiru,2023-05-24,"Balcony, Gym, Parking, Swimming Pool, Garden, Borehole","Scenic View, Golf Course",nan,https://www.buyrentkenya.com/listings/6-bedroom-villa-for-sale-nanyuki-3601569

In [14]:
(
    houses_for_sale_df
    .value_counts(subset=['agent_name'], normalize=True)
    .sort_values(ascending=False)
    .head(20)
)

agent_name
Litana Investments                  0.049194
Pam Golding Properties              0.040513
Furaha Properties                   0.036792
Mapema Properties                   0.033898
Benford Homes                       0.031418
Coral Property International Ltd    0.029764
Tysons Limited                      0.023563
Sky Miles Properties                0.022323
Leti Realty Limited                 0.018603
Nairobi Royal Homes                 0.018189
Leilach Properties                  0.018189
Geoscape Global Limited             0.015296
Abdul Kalume Realtors               0.011988
Skybraze homes                      0.011988
Splendor Holdings                   0.011988
Crystal Valuers LTD                 0.011988
Pemukika Agency                     0.011162
Afrique Properties Limited          0.011162
Ace Realtors Limited                0.011162
Jubilee Real Estate                 0.010335
dtype: float64

In [15]:
(
    houses_for_sale_df[['price', 'agent_name']]
    .groupby('agent_name')
    .agg({'price': ['mean', 'median', 'min', 'max']})
    .sort_values(('price', 'mean'), ascending=False)
)

                            price
                             mean        median           min           max
agent_name
BuyRentKenya         2.000000e+10  2.000000e+10  2.000000e+10  2.000000e+10
magdalene Kingori    5.500000e+08  5.500000e+08  5.500000e+08  5.500000e+08
Wilson Waita         2.800000e+08  2.800000e+08  2.800000e+08  2.800000e+08
Nairobi Royal Homes  2.026920e+08  1.300000e+08  3.200000e+07  6.500000e+08
Archstone Realtors   1.990000e+08  1.990000e+08  1.990000e+08  1.990000e+08
...                           ...           ...           ...           ...
Mizizi Africa Homes  5.925000e+06  5.750000e+06  5.250000e+06  6.950000e+06
Diani Holiday Homes  5.925000e+06  5.750000e+06  5.250000e+06  6.950000e+06
Kijani Annex         5.925000e+06  5.750000e+06  5.250000e+06  6.950000e+06
RockSand Homes       4.500000e+06  4.500000e+06  4.500000e+06  4.500000e+06
ODAH LIMITED         2.700000e+06  2.700000e+06  2.700000e+06  2.700000e+06

[264 rows x 4 columns]

- The summary output above shows that BuyRentKenya had the highest average price of houses
- After checking there is only one house posted by BuyRentKenya
- It is also indicated that the house is a test house
- We are going to drop it

In [16]:
### drop house posted by BuyRentKenya
houses_for_sale_df = houses_for_sale_df[houses_for_sale_df['agent_name'] != 'BuyRentKenya']

In [17]:
(
    houses_for_sale_df[['price', 'agent_name']]
    .groupby('agent_name')
    .agg({'price': ['mean', 'median', 'min', 'max']})
    .sort_values(('price', 'mean'), ascending=False)
)

                                    price                            \
                                     mean       median          min
agent_name
magdalene Kingori            5.500000e+08  550000000.0  550000000.0
Wilson Waita                 2.800000e+08  280000000.0  280000000.0
Nairobi Royal Homes          2.026920e+08  130000000.0   32000000.0
Archstone Realtors           1.990000e+08  199000000.0  199000000.0
Durian Property Consult Ltd  1.909500e+08   44000000.0   13000000.0
...                                   ...          ...          ...
Mizizi Africa Homes          5.925000e+06    5750000.0    5250000.0
Diani Holiday Homes          5.925000e+06    5750000.0    5250000.0
Kijani Annex                 5.925000e+06    5750000.0    5250000.0
RockSand Homes               4.500000e+06    4500000.0    4500000.0
ODAH LIMITED                 2.700000e+06    2700000.0    2700000.0


                                     max
agent_name
magdalene Kingori            550000000.0
Wilson Waita                 280000000.0
Nairobi Royal Homes          650000000.0
Archstone Realtors           199000000.0
Durian Property Consult Ltd  880000000.0
...                                  ...
Mizizi Africa Homes            6950000.0
Diani Holiday Homes            6950000.0
Kijani Annex                   6950000.0
RockSand Homes                 4500000.0
ODAH LIMITED                   2700000.0

[263 rows x 4 columns]

In [18]:
houses_for_sale_df[houses_for_sale_df['agent_name'] == 'magdalene Kingori']

,listing_title,price,bedrooms,bathrooms,agent_name,date_created,internal_features,external_features,nearby,link
169,10 Bed Villa at Comboni,550000000.0,10.0,10.0,magdalene Kingori,2023-05-25,nan,nan,nan,https://www.buyrentkenya.com/listings/10-bedroom-villa-for-sale-karen-3597457

- You can also consider lumping the agents with less than 5 houses into one category
- This will help treating agent with only one house that is expensive as an outlier

In [19]:
## split the title into location and house type by either at or in
def sep_title(x):
    if 'at' in x:
        return x.split('at')[-1]
    elif 'in' in x:
        return x.split('in')[-1]
    else:
        return None

houses_for_sale_df['location'] = houses_for_sale_df['listing_title'].apply(sep_title)

In [20]:
## reorder location to the first column
houses_for_sale_df = houses_for_sale_df[['location', 'listing_title', 'price', 'date_created', 'agent_name', 'internal_features', 'external_features', 'nearby', 'link']]
houses_for_sale_df.head()

,location,listing_title,price,date_created,agent_name,internal_features,external_features,nearby,link
0,Westlands Area,4 Bed Townhouse with En Suite in Westlands Area,40000000.0,2023-07-04,Origin Homes,"Alarm, Backup Generator, En Suite, Fibre Internet, Walk In Closet","BBQ, Parking, Staff Quarters, CCTV, Electric Fence, Borehole, Garden","Bus Stop, Shopping Centre, Golf Course, Scenic View, Hospital, School",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-westlands-area-3612765
1,Redhill,4 Bed Townhouse with En Suite in Redhill,40000000.0,2023-07-07,Edlon Group Limited,En Suite,"Electric Fence, Garden, Parking",Scenic View,https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-red-hill-4-3460895
2,Bamburi Mwisho,4 Bed House with Walk In Closet at Bamburi Mwisho,15000000.0,2023-07-04,Abdul Kalume Realtors,"Furnished, Walk In Closet","Balcony, Parking, Staff Quarters","Bus Stop, Hospital, School, Golf Course, Scenic View",https://www.buyrentkenya.com/listings/furnished-4-bedroom-house-for-sale-bamburi-1-3482311
3,Olive Place Townhomes,4 Bed Townhouse with En Suite at Olive Place Townhomes,12500000.0,2023-06-30,Olive Place,"En Suite, Service Charge Included, Walk In Closet, Fibre Internet","Balcony, CCTV, Electric Fence, Borehole, Parking","School, Hospital, Bus Stop, Shopping Centre, Scenic View",https://www.buyrentkenya.com/listings/4-bedroom-townhouse-for-sale-gikambura-1-3578132
4,Nanyuki,6 Bed Villa with Swimming Pool at Nanyuki,60000000.0,2023-05-24,Precious Wanjiru,"Balcony, Gym, Parking, Swimming Pool, Garden, Borehole","Scenic View, Golf Course",nan,https://www.buyrentkenya.com/listings/6-bedroom-villa-for-sale-nanyuki-3601569

- The location is not very precise
- You can get more precise location by performing further cleaning

In [21]:
## save the data
houses_for_sale_df.to_csv('houses_for_sale_cleaned.csv', index=False)